version: '3'
services:
  flask:
    # Путь до Dockerfile
    build: ./blog_app
    # Имя для создаваемого контейнера
    container_name: my-first-container
    # Создание переменных окружения в контейнере
    environment:
      # для отладки (при запуске в релиз убрать!)
      - FLASK_ENV=development
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
      ##
    # Перезапускаем сервис в случае падения
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./:/blog_app
    # Открываем порт в контейнер - ./blog_app:/blog_app
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:5000"
    command: gunicorn run:"start_app()" -b 0.0.0.0:5000 --reload